SC-TechDev/DevOps-Scripts

azure-quickstart-templates/README.md, azure-quickstart-templates/rancher-cattle-host-scaling-group/README.md, azure-quickstart-templates/rancher-cattle-host-scaling-group/addfileshare.sh, azure-quickstart-templates/rancher-cattle-host-scaling-group/azuredeploy.json, azure-quickstart-templates/rancher-cattle-host-scaling-group/azuredeploy.parameters.json, azure-quickstart-templates/rancher-cattle-host-scaling-group/startup.sh, azure-quickstart-templates/rancher-server-scaling-group/README.md, azure-quickstart-templates/rancher-server-scaling-group/azuredeploy.json, azure-quickstart-templates/rancher-server-scaling-group/azuredeploy.parameters.json, azure-quickstart-templates/rancher-server-scaling-group/rancherha.sh, azure-quickstart-templates/rancher-server-scaling-group/startup.sh, azure-quickstart-templates/scripts/rancherautojoin.py
will create 3 more PR's for updating file URI's for azuredeploy.json and then for parameters.json and last one for readme.md
=> moving azure quickstart templates

azure-quickstart-templates/docker-scaling-group-externallbvnet/README.md, azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.parameters.json, azure-quickstart-templates/docker-scaling-group-externallbvnet/startup.sh
@ronnytag233 simple Docker VM template for use outside Rancher
=> adding docker vm template

azure-quickstart-templates/docker-scaling-group-externallbvnet/README.md, azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.parameters.json
@ronnytag233 further reduced the template
=> removing loadbalancer it is not required

azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.parameters.json
=> removing lb parameters

azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.parameters.json
@ronnytag233 to allow disk size to be increased for future scale sets.
=> parameterize size of Docker disk

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/README.md, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.parameters.json, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/rancherha.sh, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/startup.sh
=> Update rancherha script

azure-quickstart-templates/docker-scaling-group-externallbvnet/README.md
@ronnytag233 needed to add disksize description to readme
=> forgot to update readme

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.parameters.json
=> remove lb from rancher external scaling group

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.parameters.json
@ronnytag233 another review please.
=> fixing a couple errors

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.parameters.json, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/rancherha.sh, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/startup.sh
=> more updates

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/README.md, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/startup.sh, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/rancherha.sh, azure-quickstart-templates/scripts/rancherautojoin.py
=> Updating ip in scripts

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/README.md, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/startup.sh
@ronnytag233 couple updates for Cattle deploy
=> Ready cattle template for production

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.parameters.json
@ronnytag233 need review, adds scaling group to existing backend pool, the GUI won't allow people to do this.
=> updating rancher server scaling group to join backend pool

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json
@ronnytag233 bepool addition for cattle
=> adding in backend pool addition to script

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json
=> adding in new rancher environments

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json
Need a squirrel.  Had to remove a bunch of stuff for VNET Peering that was not removed and also fixed a bad comma situation.
=> updates for external vnet cattle

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.json
=> trying subshell

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.json
=> updating cattle with subshell command

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.json
@ronnytag233 wrapping var values in double quotes
=> wrapping all var values with double quotes

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json
=> finally found it!

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.json, azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json
@ronnytag233 should produce a single storage account per host plus i bumped vmss length
=> updates for storage

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json
=> put storage name over limit shortening to prod here

azure-quickstart-templates/docker-scaling-group-externallbvnet/startup.sh
=> updating version schema

azure-quickstart-templates/rancher-server-scaling-group/rancherha.sh
=> upgrading rancher version

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/azuredeploy.parameters.json, azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/azuredeploy.json
@ronnytag233 this fixes issue with vars not sending to shell script
=> fixes issues with vars not working with bash shell script

azure-quickstart-templates/rancher-server-scaling-group/rancherha.sh
=> update to 1.6.4

azure-quickstart-templates/scripts/rancherautojoin.py
@dustinvanbuskirk please review
=> Performance and code style improvements for rancherautojoin.py

azure-quickstart-templates/rancher-server-scaling-group/rancherha.sh
=> need to update version here

azure-quickstart-templates/rancher-server-scaling-group/rancherha.sh
=> try out version 2 with ACS

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/startup.sh
=> updating docker installation for 17+

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/startup.sh
=> updating to allow for unattended install

azure-quickstart-templates/rancher-cattle-host-scaling-group-externallbvnet/startup.sh
=> updating to dockerd

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/rancherha.sh, azure-quickstart-templates/rancher-server-scaling-group/rancherha.sh
=> adding in a while loop to wait for rancher-ha to start

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/rancherha.sh
=> updating for correct file location

azure-quickstart-templates/rancher-server-scaling-group-externallbvnet/rancherha.sh, azure-quickstart-templates/rancher-server-scaling-group/rancherha.sh
@ronnytag233 might want to note this backtic weirdness for other shell scripts but you know I am a Python fanboy...
=> the script does not like the backtics

azure-quickstart-templates/docker-scaling-group-externallbvnet/startup.sh
=> using correct Docker install scripting

azure-quickstart-templates/docker-scaling-group-externallbvnet/azuredeploy.parameters.json, azure-quickstart-templates/docker-scaling-group-externallbvnet/startup.sh
=> updating docker start exec
